name: Generate Scorecard

on:
  push:
    paths:
    - 'config.txt'

jobs:
  generate-scorecard:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Scorecard
        run: |
          go install github.com/ossf/scorecard/v5@latest
      - name: Create Reports
        run: |
          python generate_scorecard.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updating the markdown files"
          git push