name: Scorecard

on:
  push:
    paths:
    - 'config.txt'

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          python-version: '1.21'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Scorecard
        run: |
          go install github.com/ossf/scorecard/v5@latest
